image:
  file: .gitpod.Dockerfile

# better to avoid the create because if we change something in the requirements
# create has already taken the ones from the Git repository
# tasks:
#  - before: molecule create # executed on every start and is expected to terminate

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
