---
roles:
  # Install a role from Ansible Galaxy.
  - name: petermosmans.customize-gnome
    version: 0.2.10
    # src: https://github.com/LorenzoBettini/ansible-role-customize-gnome
    # version: "issue-15"

collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
    # version: 6.4.0
    # pin older version until https://github.com/ansible-collections/community.general/issues/6271 is fixed