- name: Install Flatpak
  become: true
  ansible.builtin.package:
    state: present
    name:
    - flatpak

- name: Add the flathub flatpak repository remote
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
#    method: user

# To remove the filters on flathub introduced by Fedora
# see https://ask.fedoraproject.org/t/ansible-flathub-repo-setup/19176
# see https://fedoraproject.org/wiki/Changes/Filtered_Flathub_Applications
- name: Remove filters from flathub
  become: true
  ansible.builtin.command:
    cmd: flatpak remote-modify --no-filter flathub 
  changed_when: false
