# Required for unzipping extension archives
- name: Install Unzip
  become: true
  ansible.builtin.package:
    state: present
    name:
    - unzip

# Downloading extensions is very flaky, so if it succeeds on 'converge'
# we skip it on 'idempotence'
- name: Install Gnome Extensions
  ansible.builtin.include_role:
    name: petermosmans.customize-gnome
  tags: molecule-idempotence-notest
  vars:
    gnome_extensions:
      - id: 19 # User Theme "user-theme@gnome-shell-extensions.gcampax.github.com"
      - id: 615 # AppIndicator and KStatusNotifierItem Support
      - id: 3740 # Magic Lamp "compiz-alike-magic-lamp-effect@hermes83.github.com"
      - id: 307 # dash-to-dock "dash-to-dock@micxgx.gmail.com"
      - id: 973 # switcher "switcher@landau.fi"
      - id: 779 # clipboard-indicator
      - id: 1112 # screenshot-tool
      - id: 7 # removable-drive-menu
      # - id: 3088 # extension-list
      # - id: 97 # Coverflow Alt-Tab
      # - id: 16 # Auto Move Windows
      # - id: 10 # windowNavigator
      # - id: 5004 # dash-to-dock-for-cosmic
      # - id: 2890 # Tray Icons: Reloaded, works with Dropbox in Gnome 42!
      # - id: 120 # system-monitor
      # - id: 3843 # just-perfection
      # - id: 4033 # x11-gestures "x11gestures@joseexposito.github.io" requires touchegg
