# the default was ['.trackerignore', '.git', '.hg', '.nomedia']
# but that way the contents of a git working directory are not indexed
- name: Customize Tracker Ignored directories with content
  community.general.dconf:
    key: "/org/freedesktop/tracker/miner/files/ignored-directories-with-content"
    value: "['.trackerignore', '.hg', '.nomedia']"
    state: present
  when: modify_dconf

- name: Customize Tracker Ignored directories
  community.general.dconf:
    key: "/org/freedesktop/tracker/miner/files/ignored-directories"
    value: "['po', 'CVS', 'core-dumps', 'lost+found', 'bin', 'test-bin', 'bin-test', 'target', 'xtend-gen', 'src-gen', 'cache', 'node_modules', 'node_packages', 'thunderbird']"
    state: present
  when: modify_dconf

- name: Make sure Tracker 3 is installed (Arch)
  become: true
  ansible.builtin.package:
    state: present
    name:
    - tracker3
    - tracker3-miners
  when: ansible_os_family == 'Archlinux'

- name: Make sure Tracker 3 is installed (Not Arch)
  become: true
  ansible.builtin.package:
    state: present
    name:
    - tracker
    - tracker-miners
  when: ansible_os_family != 'Archlinux'

- name: Make sure Tracker 2 is NOT installed (Arch)
  become: true
  ansible.builtin.package:
    state: absent
    name:
    - tracker
    - tracker-miners
  when: ansible_os_family == 'Archlinux'

- name: Disable tracker-extract
  become: true
  ansible.builtin.shell: >
    mkdir -p ~/tmp/extract-rules && \
    find /usr/share/tracker3-miners/extract-rules/ -name "*.rule" -exec mv {} ~/tmp/extract-rules/ \; && \
    chown -R {{ ansible_user_id }}:{{ ansible_user_id }} ~/tmp/extract-rules
  changed_when: false