# the default was ['.trackerignore', '.git', '.hg', '.nomedia']
# but that way the contents of a git working directory are not indexed
- name: Customize Tracker Ignored directories with content
  community.general.dconf:
    key: "/org/freedesktop/tracker/miner/files/ignored-directories-with-content"
    value: "['.trackerignore', '.hg', '.nomedia']"
    state: present
  when: modify_dconf

- name: Customize Tracker Ignored directories
  community.general.dconf:
    key: "/org/freedesktop/tracker/miner/files/ignored-directories"
    value: "['po', 'CVS', 'core-dumps', 'lost+found', 'bin', 'test-bin', 'bin-test', 'target', 'xtend-gen', 'src-gen', 'cache', 'node_modules', 'node_packages', 'thunderbird']"
    state: present
  when: modify_dconf

- name: Make sure Tracker 3 is installed (Arch)
  become: true
  ansible.builtin.package:
    state: present
    name:
    - tracker3
    - tracker3-miners
  when: ansible_os_family == 'Archlinux'

- name: Make sure Tracker 3 is installed (Fedora)
  become: true
  ansible.builtin.package:
    state: present
    name:
    - tracker
    - tracker-miners
  when: ansible_distribution == 'Fedora'

- name: Make sure Tracker 3 is installed (Ubuntu)
  become: true
  ansible.builtin.package:
    state: present
    name:
    - tracker
  when: ansible_distribution == 'Ubuntu'

- name: Make sure Tracker 2 is NOT installed (Arch)
  become: true
  ansible.builtin.package:
    state: absent
    name:
    - tracker
    - tracker-miners
  when: ansible_os_family == 'Archlinux'

- name: Parse Gnome Shell version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      gnome-shell --version | sed 's/^[^0-9.]*//' | sed 's/[^0-9]*$//'
    executable: /bin/bash
  register: r_gnome_extension_parse_shell_version
  changed_when: false

- name: Set Gnome Shell version as parameter
  ansible.builtin.set_fact:
    gnome_shell_version: "{{ r_gnome_extension_parse_shell_version.stdout }}"

- name: Check if Gnome Shell was detected
  ansible.builtin.debug:
    msg: "Sorry - no Gnome Shell detected... exiting"
  failed_when: true
  when: not r_gnome_extension_parse_shell_version.stdout

- name: Check if the directory "/usr/share/localsearch3" exists
  ansible.builtin.stat:
    path: /usr/share/localsearch3
  register: localsearch3_check

- name: Disable tracker-extract (tracker3-miners)
  become: true
  ansible.builtin.shell: >
    mkdir -p ~/tmp/extract-rules && \
    find /usr/share/tracker3-miners/extract-rules/ -name "*.rule" -exec mv {} ~/tmp/extract-rules/ \; && \
    chown -R {{ ansible_user_id }}:{{ ansible_user_id }} ~/tmp/extract-rules
  when: not localsearch3_check.stat.exists
  changed_when: false

# In Gnome 47 tracker and miners have a different name
# https://discourse.gnome.org/t/renaming-tracker-git-and-tracker-sparql-git-and-changing-default-branch/21461
# But in Fedora 41 they seem to have gonve back to the old name
- name: Disable tracker-extract (localsearch3)
  become: true
  ansible.builtin.shell: >
    mkdir -p ~/tmp/extract-rules && \
    find /usr/share/localsearch3/extract-rules/ -name "*.rule" -exec mv {} ~/tmp/extract-rules/ \; && \
    chown -R {{ ansible_user_id }}:{{ ansible_user_id }} ~/tmp/extract-rules
  when: localsearch3_check.stat.exists
  changed_when: false