---
# tasks file for my_gnome_role
- name: System details
  ansible.builtin.debug:
    msg: "{{ item }}"
  with_items: 
  - "ansible_os_family: {{ ansible_os_family }}"
  - "ansible_distribution: {{ ansible_distribution }}"
  - "ansible_distribution_release: {{ ansible_distribution_release }}"
  - "ansible_distribution_version: {{ ansible_distribution_version }}"
  - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"

- name: Install Gnome Packages
  become: true
  ansible.builtin.package:
    state: present
    name:
    - gnome-shell
    - gnome-tweaks
    - dconf-editor
    - xdg-utils # required for xdg-mime below
    - gnome-screenshot # the original screenshot application
    - baobab
    - deja-dup
    - eog
    - evince
    - evolution
    - file-roller
    - gnome-backgrounds
    - gnome-calculator
    - gnome-calendar
    - gnome-contacts
    - gnome-logs
    - gnome-remote-desktop
    - gnome-system-monitor
    - gnome-text-editor
    - gnome-weather
    - simple-scan
    - gvfs

# removed in Ubuntu Noble, I'm not using it anyway
#    - gnome-photos

- name: Override python-psutil package name for Arch.
  ansible.builtin.set_fact:
    python_psutil: python-psutil
  when: ansible_os_family == 'Archlinux'

- name: Install Python psutil
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ python_psutil }}"

- name: Tasks for Guake Drop-down Terminal
  ansible.builtin.include_tasks: guake.yml

- name: Tasks for ArchLinux
  ansible.builtin.include_tasks: gnome-arch.yml
  when: ansible_os_family == 'Archlinux'

- name: Tasks for Template files
  ansible.builtin.include_tasks: gnome-templates.yml

- name: Tasks for Gnome Tracker
  ansible.builtin.include_tasks: gnome-tracker.yml

- name: Tasks for Gnome configuration
  ansible.builtin.include_tasks: gnome-configurations.yml

- name: Tasks for Gnome extensions
  ansible.builtin.include_tasks: gnome-extensions.yml

- name: Tasks for Flatpak
  ansible.builtin.include_tasks: flatpak.yml
  when: with_flatpak

- name: Tasks for Gnome Extension Manager
  ansible.builtin.include_tasks: gnome-extension-manager.yml
  when: with_flatpak
