---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Assert flatpak is NOT installed in this scenario
    ansible.builtin.shell: >
      flatpak --version
    register: flatpak_cmd
    failed_when: flatpak_cmd.rc == 0
    changed_when: false
