# tracker-extract cannot be disabled anymore by masking a service in Gnome 46
# see https://discourse.gnome.org/t/can-tracker-extract-be-disabled-in-gnome-46/20782

# In previous versions of ubuntu the service file was
# tracker-extract.service
# In more recent versions is
# tracker-extract-3.service
- name: Disable Tracker Extract
  tags: molecule-notest
  ansible.builtin.systemd:
    name: tracker-extract-3
    scope: user
    masked: yes
# Don't run that in Molecule: it succeeds with a Docker without systemd
# but it fails when running in a Docker with systemd.
# Previously we masked it at the global level
# so that it can be run also in a chroot environment
# otherwise we get "Failed to connect to bus: No such file or directory"
# This is required only if run while installing Arch.
# However, when running this in a real Ubuntu, the mask silently fails
# (see https://github.com/LorenzoBettini/my_gnome_role/issues/12)
# at system level; better to mask it at user level.
